/**
 * Generates TypeScript types from Soroban contract spec.
 *
 * Usage: npm run gen:contracts
 *
 * Reads contract spec JSON files from a directory and generates
 * TypeScript type definitions for use in the frontend.
 *
 * TODO: Integrate with actual Soroban contract bindings when
 * the contract specs are available.
 */

import fs from "node:fs"
import path from "node:path"

const SPECS_DIR = path.resolve(__dirname, "../contract-specs")
const OUTPUT_DIR = path.resolve(__dirname, "../src/lib/contracts")

interface ContractSpec {
  name: string
  functions: Array<{
    name: string
    inputs: Array<{ name: string; type: string }>
    outputs: Array<{ type: string }>
  }>
  types: Array<{
    name: string
    fields: Array<{ name: string; type: string }>
  }>
}

function loadSpecs(dir: string): ContractSpec[] {
  if (!fs.existsSync(dir)) {
    console.warn(`Contract specs directory not found: ${dir}`)
    console.warn(
      "Place your Soroban contract spec JSON files in the contract-specs/ directory.",
    )
    return []
  }

  const files = fs.readdirSync(dir).filter((f) => f.endsWith(".json"))
  return files.map((file) => {
    const raw = fs.readFileSync(path.join(dir, file), "utf-8")
    return JSON.parse(raw) as ContractSpec
  })
}

function generateTypeScript(specs: ContractSpec[]): string {
  const lines: string[] = [
    "// Auto-generated contract types — do not edit manually",
    "// Generated by: npm run gen:contracts",
    "",
  ]

  for (const spec of specs) {
    lines.push(`// Contract: ${spec.name}`)

    // Generate type definitions
    for (const type of spec.types) {
      lines.push(`export interface ${type.name} {`)
      for (const field of type.fields) {
        const tsType = mapScValToTs(field.type)
        lines.push(`  ${field.name}: ${tsType}`)
      }
      lines.push("}")
      lines.push("")
    }

    // Generate function input/output types
    for (const fn of spec.functions) {
      const fnName = capitalize(fn.name)
      if (fn.inputs.length > 0) {
        lines.push(`export interface ${fnName}Input {`)
        for (const input of fn.inputs) {
          lines.push(`  ${input.name}: ${mapScValToTs(input.type)}`)
        }
        lines.push("}")
        lines.push("")
      }
      if (fn.outputs.length > 0) {
        lines.push(`export type ${fnName}Output = ${mapScValToTs(fn.outputs[0].type)}`)
        lines.push("")
      }
    }
  }

  if (specs.length === 0) {
    lines.push("// No contract specs found.")
    lines.push("// Add JSON spec files to contract-specs/ directory.")
    lines.push("export {}")
  }

  return lines.join("\n")
}

function mapScValToTs(scValType: string): string {
  const mapping: Record<string, string> = {
    u32: "number",
    u64: "bigint",
    i32: "number",
    i64: "bigint",
    i128: "bigint",
    u128: "bigint",
    u256: "bigint",
    i256: "bigint",
    bool: "boolean",
    symbol: "string",
    string: "string",
    bytes: "Uint8Array",
    address: "string",
    void: "void",
  }
  return mapping[scValType] ?? scValType
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

function main(): void {
  const specs = loadSpecs(SPECS_DIR)

  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true })
  }

  const output = generateTypeScript(specs)
  const outputPath = path.join(OUTPUT_DIR, "contract-types.ts")
  fs.writeFileSync(outputPath, output, "utf-8")

  console.log(`Generated contract types: ${outputPath}`)
}

main()
